### ISSUE TITLE
Debris wrong when in Multiple Panes

### ISSUE THREAD

**Issue by elpollitodiablo** [JoelBesada/activate-power-mode#106]
First of all I <3 IT! But ...

When I have split panes, the pane shakes when typing but the 'debris' is only flying in the main pane.

OS: Win 7 Pro 64bit 
Atom: 1.5.4
activate-power-mode: 0.4.1

**Comment by akoumjian** [comment]
I can second. 

OSX 10.11.3
Atom 1.5.4
activate-power-mode: 0.4.1

**Comment by lexcast** [comment]
already fixed, use the latest version
