### ISSUE TITLE
Particle Bug in HTML5

### ISSUE THREAD

**Issue by montesajudy** [JoelBesada/activate-power-mode#107]
I am having a problem with using this in HTML5. The particles are showing at the bottom of the screen instead of beside the letter i am typing at.

**Comment by lexcast** [comment]
what do you mean with *using this in HTML5*?

**Comment by nathanchapman** [comment]
This occurs in any HTML file

**Comment by lexcast** [comment]
Hehe silly question

**Comment by Juu-Dee** [comment]
What I mean is that, when I am typing in other file like for example a CSS file, the particles are showing correctly beside the letter I am currently typing. However in a HTML file, the particles does not show beside the letter, instead it shows at the very bottom of the page.

**Comment by lexcast** [comment]
Thank you @Juu-Dee 
Are you using hard tabs or soft wrap on html files?
This issue is not the same as others related with soft wrap or tabs

**Comment by lexcast** [comment]
Closing issues on old versions of this package.

Open again if the problem persists with the latest release.
