### ISSUE TITLE
random particule

### ISSUE THREAD

**Issue by Draec** [JoelBesada/activate-power-mode#109]
On windows 7 the particule explose ererywhere in the panel. The particul does not follow the cursor.

**Comment by abniyaz** [comment]
The particul does not follow the cursor in ubuntu 15.0 as well.

**Comment by lexcast** [comment]
are you using tabs or soft wrap?

**Comment by abniyaz** [comment]
soft wrap

**Comment by lexcast** [comment]
already fixed, use the latest version
