### ISSUE TITLE
Some wrongs in more than two panes

### ISSUE THREAD

**Issue by CocherZhang** [JoelBesada/activate-power-mode#112]
if there are two or more panes, all the particles will show in one pane

**Comment by febLey** [comment]
I can confirm this, i'm having the same issue

**Comment by alvaropinot** [comment]
+1
particles will show only in right panel

**Comment by ManBearPigg** [comment]
When left and right pane are open simultaneously, and I type in the right pane, the effect is rendered in the left pane.

**Comment by shellqiqi** [comment]
+1
I also have the same issue

**Comment by lexcast** [comment]
already fixed, use the latest version
