### ISSUE TITLE
Particle bug when indent using soft tab

### ISSUE THREAD

**Issue by EntropyIncreaser** [JoelBesada/activate-power-mode#116]
When I type behind some <kbd>tab</kbd>, the particle isn't with my cursor, it is in front of my cursor. Just like this:  
![preview](http://d.pcs.baidu.com/thumbnail/9f54e88abc71a4cfd81e37e58b1ae13d?fid=524990511-250528-804184299330521&time=1459753200&rt=sh&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-fhBbnkqpihDU91SG3SVy1KZ6Kt0%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=2194891447633586994&dp-callid=0&size=c710_u500&quality=100)

**Comment by lexcast** [comment]
the preview image is broken, can you upload again?

**Comment by lexcast** [comment]
check if the latest version fixes this
