### ISSUE TITLE
Only works on the left side column...

### ISSUE THREAD

**Issue by Nav31** [JoelBesada/activate-power-mode#122]

**Comment by mikeatlas** [comment]
Yeah, seeing the same thing - two panes (my usual setup on a 16:9 resolution) doesn't work on the right pane.

**Comment by mikeatlas** [comment]
Same as #118

**Comment by mikeatlas** [comment]
and #112

**Comment by mikeatlas** [comment]
and #106

**Comment by Bango1999** [comment]
It's true that when panes are split, the package has bugs.  I'm trying a bunch of splits, and 1 pane (the original pane) has the confetti/ash effect, another pane has the earthquake effect, and the other panes have nothing, even if they are the active pane.

**Comment by lexcast** [comment]
already fixed, use the latest version
