### ISSUE TITLE
Consistently on wrong line in all file types on Atom 1.7.1

### ISSUE THREAD

**Issue by PascalPencil** [JoelBesada/activate-power-mode#126]
.erb .scss .haml .html .rb - For me it grabs the wrong line every time, sometimes one, sometimes 2 or 3, seems like a fun thing if it works though!

**Comment by lexcast** [comment]
it happens with soft wrap?

**Comment by PascalPencil** [comment]
Correct, it's soft wrap

**Comment by lexcast** [comment]
already fixed, use the latest version
