### ISSUE TITLE
position mismatch when soft wrap option is enabled

### ISSUE THREAD

**Issue by cless00** [JoelBesada/activate-power-mode#127]
position calculation is not considering the soft-wrapped sentenses by atom.

![capture](https://cloud.githubusercontent.com/assets/11464204/14593890/2f1373ba-056b-11e6-87f6-ea29e6447bc5.PNG)

**Comment by Bango1999** [comment]
Confirmed in 0.4.1.

**Comment by lexcast** [comment]
already fixed, use the latest version
