### ISSUE TITLE
particles are not working

### ISSUE THREAD

**Issue by mattds9** [JoelBesada/activate-power-mode#128]

**Comment by MikeJKBird** [comment]
The particles only work for me when I first open Atom. Opening another document within a project causes the particles no longer appear. Only the shake happens. Switching back to the first document does not fix the issue, and particles only appear after closing and re-opening atom.

**Comment by nikcheerla** [comment]
The same thing happens for me.

**Comment by deadlybutter** [comment]
restarting the editor worked for me, weird

**Comment by DevMaterial** [comment]
Particles worked for me a couple minutes after I toggled it. After those few minutes, the particle effect stopped.

**Comment by lexcast** [comment]
@mattds9 can you describe your issue?

**Comment by lexcast** [comment]
Closing issues on old versions of this package.

Open again if the problem persists with the latest release.
