### ISSUE TITLE
If I use soft warp, the activate-power will appear on the up line

### ISSUE THREAD

**Issue by SuperTian007** [JoelBesada/activate-power-mode#133]
I use Atom 1.7.2, when I write Chinese or English with activate-power-mode on, if I use soft wrap, the activate-power will happen on the up lines.
![image](https://cloud.githubusercontent.com/assets/11640301/14762122/61649a04-09a5-11e6-8a78-6e562297997d.png)

**Comment by DesiQuintans** [comment]
Yup, experiencing the same issue. It's very noticeable when you're trying to write a Markdown document, because a single paragraph takes up a single line and it can soft-wrap across many rows.

**Comment by bovas85** [comment]
Yeah the soft wrap messes with the row particle placement. Fun package though, thumbs up

**Comment by lexcast** [comment]
already fixed, use the latest version
