### ISSUE TITLE
Activate power mode when typing faster than x keys per second

### ISSUE THREAD

**Issue by kctang** [JoelBesada/activate-power-mode#135]
Sounds cool if we can let power mode auto kicks in when kps is > x. It should deactivate when user slows down typing. What do you guys think? :-)

**Comment by mjurczyk** [comment]
@JoelBesada anything on that matter :D ?

**Comment by lexcast** [comment]
The #264 provides a way to achieve this.

**Comment by lexcast** [comment]
Closing as this can be achieved by using the new Flow functionality.
https://github.com/JoelBesada/activate-power-mode/wiki/Flow
