### ISSUE TITLE
Mac: `ctrl` + `opt` + `o` not working

### ISSUE THREAD

**Issue by halfnibble** [JoelBesada/activate-power-mode#145]
I don't know if I am the only person experiencing this, but even though the keyboard shortcut is enabled, typing it has no affect on enabling or disabling.

Using the dropdown menu works.

**Comment by lexcast** [comment]
For me isn't working neither. But my keybindings are a mess, so I'm not 100% sure.
I've seen many packages that remove these keybindings and just put a keybinding in the readme to let the users copypaste.

**Comment by The-Penultimate-Defenestrator** [comment]
Works for me. I'm also on OS X.

**Comment by lexcast** [comment]
I've removed some conflicts in my keybindings and it's working.

@halfnibble check if there is another package with the same keyboard shortcut.
