### ISSUE TITLE
Incorrect particle colour

### ISSUE THREAD

**Issue by hexus** [JoelBesada/activate-power-mode#146]
I have an issue, similar to #101, except the particles are rendering in white in _some_ cases.

Some colours don't have this issue at all. I'm using my own syntax theme, (https://www.github.com/darya/syntax).

The colour shows up rarely if I hold down a key, as shown below.

![atom-power-mode-particle-colour-issue](https://cloud.githubusercontent.com/assets/2626789/15094197/e4a49596-1494-11e6-8424-0515b06a101a.png)

This is only happening after the last dot notation of an expression.

So if I type here (in bold):

<pre>
<b>My.Object</b>.IsVeryCool
</pre>

Everything is fine, but any typing here, or when introducing new lines like this:

<pre>
My.Object.<b>IsVeryCool</b>
</pre>

The colour is incorrect for the majority of key presses.

**Comment by lexcast** [comment]
I think the particle color is taken from the next character on the buffer change. In the case of your screenshot, the semicolon is white, so the particles are white as well.

**Comment by hexus** [comment]
I see, so when introducing code at the end of a line it's not going to pick up the colour?

**Comment by lexcast** [comment]
Yes, when that happens and no color is found, the particles will be white... unless "show invisibles" is enabled, in that case it will take the invisible character color, probably gray (#101).

**Comment by lexcast** [comment]
this should be fixed already on the current release
