### ISSUE TITLE
advice: screen shock should be triggered every time we press "enter"!

### ISSUE THREAD

**Issue by zacharyhisa** [JoelBesada/activate-power-mode#149]
Screen shocking should be triggered less, and I think the best time to trigger it is when we press "enter"

**Comment by jeffswt** [comment]
And shocking at every keystroke is lagging my computer.

**Comment by lexcast** [comment]
The #264 provides a way to achieve this.

**Comment by lexcast** [comment]
Closing as this can be achieved by using the new Flow functionality.
https://github.com/JoelBesada/activate-power-mode/wiki/Flow
