### ISSUE TITLE
Automatic Start

### ISSUE THREAD

**Issue by 13sergy** [JoelBesada/activate-power-mode#150]
I need always use ctrl+alt+o to activate. I would like activate it automatically.

**Comment by 13sergy** [comment]
Add this line to your init.coffee: (Edit>Init script)
atom.commands.dispatch(atom.views.getView(atom.workspace), 'activate-power-mode:toggle')

**Comment by lexcast** [comment]
In the package settings you can select the autoToggle checkbox.
