### ISSUE TITLE
Feature request: key stroke sounds

### ISSUE THREAD

**Issue by gnrlbzik** [JoelBesada/activate-power-mode#152]
Would be cool to have optional sounds typewriter key strokes while typing.

http://www.soundjay.com/typewriter-sounds.html

Thanks for considering.

**Comment by kozie** [comment]
+1, but needs more like something exploding or the likes, instead of a typewriter sound

**Comment by gnrlbzik** [comment]
@kozie yeah that works too, i just remember the feeling of the effect when you bounce on the keys in what ever app i used. Lots of fun : )

**Comment by adamfr33man** [comment]
Looks like someone has already done this (with gun sounds) https://github.com/JoelBesada/activate-power-mode/pull/125

**Comment by lexcast** [comment]
This is duplicated of #21
But I will leave this one open as is newer, for more exposition.

**Comment by lexcast** [comment]
There are already two pull requests with this feature #125 and #44 

IMO, typewriter sound feels more natural, so #44 is more likely to me merged when fixing conflicts.

The other PR adds gunshot sound btw :gun:

**Comment by cnHeider** [comment]
#125  is updated

**Comment by lexcast** [comment]
#125 :gun: merged.
