### ISSUE TITLE
Atom is crashing when power mode is enabled

### ISSUE THREAD

**Issue by sashamirkovic** [JoelBesada/activate-power-mode#154]
Hello,

I am using power mode 0.5.2 for atom. As soon as I enable power mode Atom starts crashing very often, with period of minutes. If I disable power mode package, atom is stable.

I do not know how to give you more data about this. 

Best Regards,
Sasha

**Comment by lexcast** [comment]
is still happening with the new version?

**Comment by lexcast** [comment]
Closing issues on old versions of this package.

Open again if the problem persists with the latest release.
