### ISSUE TITLE
Default to disabled?

### ISSUE THREAD

**Issue by eddnav** [JoelBesada/activate-power-mode#170]
How to have this disabled by default? I like to use it from time to time, in those special situations where I need to raise my power level.

**Comment by orthros** [comment]
Agreed. I can't start up at full power; I need to gradually work my way up to it.

**Comment by orthros** [comment]
Actually you can do this by going to the Settings tab in Atom, finding the package and disabling the "Auto Toggle" option
![autotoggle](https://cloud.githubusercontent.com/assets/7820716/16917292/990c91e6-4cc6-11e6-9daa-9f3638c9b6c7.png)

**Comment by eddnav** [comment]
Thanks!
