### ISSUE TITLE
Not installing, no error message

### ISSUE THREAD

**Issue by SecondThread** [JoelBesada/activate-power-mode#171]
Unless my wifi is REALLY slow or this package is ENOURMAS, I think the installer is broken. I clicked install and the bar turned from blue to blue with light and dark stripes moving left, but it has been doing that for over two hours now. There is no error message and no progress bar, so idk what is going on.

**Comment by scmx** [comment]
I just had the same problem, but on my next installation attempt it worked just fine. I noticed that it showed no number for how many installs on the first attempt, but on the second attempt that number was visible.

**Comment by lexcast** [comment]
I think the atom installer is a bit unstable.
