### ISSUE TITLE
Activate-power-mode not working on latest atom + autocomplete pos is incorrect

### ISSUE THREAD

**Issue by OctoNezd** [JoelBesada/activate-power-mode#174]
Look at this: https://github.com/atom/atom/issues/12279#issuecomment-237100387

**Comment by xekri** [comment]
This package cause Atom's split panes to auto resize .Found under macOS 10.11.6. When turn on this package and open a new pane in split view (e.g. split down the current pane) and activate one of the pane, the other pane will auto resize.

**Comment by lexcast** [comment]
Yes, I can confirm those two issues, I have already a fix for the autocomplete problem. But I need investigate about the split panes issue.

**Comment by lexcast** [comment]
The autocomplete position should be fixed.
