### ISSUE TITLE
Atom 1.9 and 1.9.1, activate-power-mode causes pane split problems

### ISSUE THREAD

**Issue by fatal1tyv** [JoelBesada/activate-power-mode#177]
After upgrading to 1.9 and use pane split down, the size of the panes will change unexpectedly when navigating between two panes. 
Disabling activate-power-mode and it goes back to normal.

**Comment by lexcast** [comment]
I can confirm this, pretty weird

**Comment by fatal1tyv** [comment]
Thanks @lexcast . The issue is fixed in 0.7.2.
