### ISSUE TITLE
After last update (0.7.3) Readme and Settings are gone

### ISSUE THREAD

**Issue by AlexanderMer** [JoelBesada/activate-power-mode#181]
After I installed last update the _Readme_ and _Settings_ section right below the package info isn't displayed.

![image](https://cloud.githubusercontent.com/assets/10071402/17462698/c24fa95c-5cc6-11e6-9244-61b133210443.png)

**Comment by lexcast** [comment]
Mmm I'm able to see it with no problem.

Maybe restarting Atom could fix the issue.

**Comment by AlexanderMer** [comment]
You're right, I it's back after a restart.
