### ISSUE TITLE
Enhancement: Add 'on backspace only' toggle.

### ISSUE THREAD

**Issue by SalomonSmeke** [JoelBesada/activate-power-mode#183]
As title. I would love to leave this enabled to empower my delete key, morph it into a Hulk Smash!

As it stands, it is difficult to have this constantly enabled, and the hotkey option just ends up disabled always.

Let me know thoughts!

**Comment by nathanchapman** [comment]
@SalomonSmeke Can you please elaborate? I don't quite understand what you're requesting

**Comment by SalomonSmeke** [comment]
Certainly, sorry for being so terse.

As it stands, power mode affects basically any keystroke. It is very funny and feels great to use but it can get tiring.

I wondered if it would be beneficial to add a toggle that could limit what triggers the "power mode" effect to only the backspace key, or something similar.

So. In theory. Instead of the effect happening always it would only happen when deleting, which should make power mode much easier to have on always, VS sometimes.

**Comment by lexcast** [comment]
This may be a setting with 3 options: all, on add and on delete.

**Comment by SalomonSmeke** [comment]
That would be a great solution.

**Comment by JoelBesada** [comment]
I agree! :+1:

**Comment by SalomonSmeke** [comment]
Though, if this is implemented as a toggle between those three options, I would suggest having 'off' as an option there as well. Otherwise the options might get a little confusing, given that you have the ability to change how it behaves in terms of reducing/incrementing the effect, but not removing.

**Comment by nathanchapman** [comment]
@SalomonSmeke we currently have enable, disable, and toggle. Disable would be what you're talking about, but I agree it might make more sense to combine this functionality.

Would `on`, `on additions only`, `on deletions only`, and `off` make more sense?
What would you all suggest for the functionality of `toggle`? Switch between the 4 options incrementally, switch between on and off, or remove the toggle command?

**Comment by lexcast** [comment]
I use the toggle command for a button on my toolbar, so I need it as an on/off switch.

**Comment by SalomonSmeke** [comment]
That's correct @nathanchapman. What @lexcast says is probably a common use case. So here are my thoughts.

A) The toggle command moves from any position to off. And from off to on.
B) The toggle command remembers the previous position and switches between that and off.
C) Keep the current "on/off" toggle. Have another setting that specifies how power mode behaves while on.

I think B makes a ton of sense from a tactile perspective (would feel right). But the toggle help-text in the settings menu would need to be very clear as to what this does. C is easier to understand as a user.

**Comment by SalomonSmeke** [comment]
To clarify. Option C would look like:

[] Screen Shake - Enabled
Turn the shaking on/off.
Shake on:
Additions () Deletions () All ()

**Comment by lexcast** [comment]
The #264 provides a way to achieve this.

**Comment by SalomonSmeke** [comment]
Cool. Huge fan. I'll leave it open so that you can close it whenever you think it's prudent.

**Comment by lexcast** [comment]
#275 tries to acomplish this one.

Meanwhile, you may try this https://github.com/JoelBesada/activate-power-mode/wiki/Flow#user-file-flow

**Comment by SalomonSmeke** [comment]
Im closing this so we dont have this dangling issue doing nothing.
