### ISSUE TITLE
WebStorm!!!!!!!

### ISSUE THREAD

**Issue by CN-Sean** [JoelBesada/activate-power-mode#19]
WebStorm!!!!!!!WebStorm!!!!!!!WebStorm!!!!!!!

**Comment by sebgeelen** [comment]
I can only agree with this man on the urge to make this available on Webstorm.

With his basic language he do express beautifully how badly web, Webstorm users, need this.

**Comment by alexgleason** [comment]
WebStorm isn't free. Also, is it web based (created using HTML/CSS/JS)? If not, this is an unrealistic request.

**Comment by taxaser** [comment]
please make this available on Webstorm!

**Comment by boltozavr** [comment]
please make this available on Webstorm! [2]

**Comment by Rad1calDreamer** [comment]
it will be awesome

**Comment by andrewchron** [comment]
webstorm and as a general plugin for intellij idea!!

**Comment by ifndefdeadmau5** [comment]
Webstorm!!!!!!!!!

**Comment by lexcast** [comment]
check out https://github.com/codeinthedark/awesome-power-mode for ports to other editors
