### ISSUE TITLE
To slow when there is a lot of lines

### ISSUE THREAD

**Issue by way2key** [JoelBesada/activate-power-mode#196]
Hello,
When I use this extension with more than 500 lines, the editor slow down to the point that is unusable!

**Comment by lexcast** [comment]
try disabling the screen shake

**Comment by jeffswt** [comment]
@way2key You should blame Chrome for not writing an efficient renderer. It's got nothing to do with lexcast's code and if we try to fix this we might end up in writing a new HTML5 renderer. :/
