### ISSUE TITLE
Audio should be disabled by default

### ISSUE THREAD

**Issue by nathanchapman** [JoelBesada/activate-power-mode#197]
I was startled when I updated the package and started typing. I don't want people freaking out when their volume is all the way up and gun shot sounds are going off. A lot of people write code in social environments, coffee shops, workspaces, etc.

While I love the combo mode, I don't like the audio at all. It seems like a niche request from a very small amount of our user base. I think the best compromise would be disabling it by default.

**Comment by lexcast** [comment]
I agree.
I don't like the audio neither.
