### ISSUE TITLE
Cannot toggle power mode off

### ISSUE THREAD

**Issue by karai17** [JoelBesada/activate-power-mode#2]
Pressing ctrl+alt+o activates power mode, but doe snot deactivate it. I had to disable the package to deactivate it.

**Comment by ScottKaye** [comment]
Steps to reproduce:

1. Open Atom to an empty file
2. Type some text
3. Right click > toggle activate-power-mode
4. Hammer your keyboard to verify it's working
5. File > New File
6. Type some text
5. Switch back to previous file (where activate-power-mode was toggled)
4. Observe lack of particles, feel sad

The event still fires in the developer console (`ActivatePowerMode was toggled!`), but does not disable screen shaking.  Particles also do not reappear in any files until Atom is restarted.

**Comment by halfnibble** [comment]
Same issue for me on Atom running under Mac OS X El Capitan. 

I may just keep it on all the time. :+1:

**Comment by JoelBesada** [comment]
Fixed in 0.4.0.
