### ISSUE TITLE
Chose Sound to play when typping.

### ISSUE THREAD

**Issue by dawsonfi** [JoelBesada/activate-power-mode#205]
I love the sound feature, and it would be great if could chose witch sound to use.

**Comment by cnHeider** [comment]
I will take a look at that :)

**Comment by cnHeider** [comment]
#207

**Comment by jeffswt** [comment]
Yes. When I was typing this for the first time with my headphones on... It really gave me a shock!!!!!!!!!!!!!!!!!

You should add a notification (or a warning) at the preferences page!!! (In case other people got astonished by this)

**Comment by lexcast** [comment]
fixed on #207 and #255
