### ISSUE TITLE
Sound will make it better

### ISSUE THREAD

**Issue by Psycho7** [JoelBesada/activate-power-mode#21]
It will be amazing if there are appropriate sounds.
Is it possible?

**Comment by Cp-022** [comment]
Imagine typing : "BOOM", "BAM", "POW"

**Comment by alexgleason** [comment]
Duplicate #28, #38

**Comment by keithjgrant** [comment]
👍  I’d love a big chunky typewriter sound, or maybe gunshots.

**Comment by lexcast** [comment]
see #152
