### ISSUE TITLE
Activate Power Mode

### ISSUE THREAD

**Issue by Heshan5** [JoelBesada/activate-power-mode#212]
The power mode package is not working please can you check on it. When I installed at the first time it worked but now it is not working.

**Comment by lexcast** [comment]
what do you mean with is not working?

**Comment by Heshan5** [comment]
When you go on type only it will work other wise it willnot work

**Comment by lexcast** [comment]
I think a screen recording would help

**Comment by Heshan5** [comment]
What kind of screen recorded

**Comment by lexcast** [comment]
like those in the readme.
Do you have enabled the combo mode? if so, the effects won't appear until you reach the combo mode threshold. 
Or try the command `Activate Power Mode: Enable`

**Comment by Heshan5** [comment]
How can I do this one Activate Power Mode: Enable

**Comment by SeerUK** [comment]
Combo counter appears to be working, but particles, and screen shaking at least no longer seem to work.

**Comment by lexcast** [comment]
Effects won't appear until you reach 50 (by default) in the combo.

**Comment by lexcast** [comment]
if that is the issue, you can set the activation threshold to be less than 50, or disable the combo modo.

**Comment by SeerUK** [comment]
Yup, that's done it for me. I didn't realise that change had occurred. Thanks for the help!

**Comment by Heshan5** [comment]
You go to setting and make right guys.
