### ISSUE TITLE
activate-power-mode doesn't start with atom even if Auto Toggle is enabled

### ISSUE THREAD

**Issue by Kurolox** [JoelBesada/activate-power-mode#213]
Title. If you need any kind of log just ask for it.

**Comment by lexcast** [comment]
do you have combo mode enabled?

**Comment by Kurolox** [comment]
Yes. I've also tried with combo mode disabled. Neither of them work. (I mean, both of them work, but none of them start with atom.)

**Comment by lexcast** [comment]
can I see your `config.cson`?

**Comment by Kurolox** [comment]
´´´
"*":
  "activate-power-mode":
    comboMode:
      activationThreshold: 1
    particles:
      colours:
        type: "random"
      size: {}
      spawnCount: {}
      totalCount: {}
    playAudio: {}
    screenShake: {}
  "autoclose-html": {}
  core:
    autoHideMenuBar: true
    disabledPackages: [
      "autocomplete-html"
    ]
  editor:
    fontSize: 16
    invisibles: {}
    tabLength: 4
  fonts:
    fontFamily: "Hack"
    preview: "The Quick brown fox { 0 !== \"O\" }asdasdsdddddddds"
  linter:
    errorPanelHeight: 40
  "linter-flake8":
    ignoreErrorCodes: [
      "D100"
      "D103"
    ]
    pep8ErrorsToWarnings: true
  "tree-view": {}
  welcome:
    showOnStartup: false
".basic.html.text":
  editor:
    tabLength: 3
´´´

**Comment by lexcast** [comment]
I can't reproduce your problem 😕 try to see if there is something related in your log

**Comment by Kurolox** [comment]
Not sure what relevant logs could be helpful. Anything in particular that you would want to see?

**Comment by Kurolox** [comment]
Nevermind, I fixed it.

Checking old fixed issues I found this one. https://github.com/JoelBesada/activate-power-mode/issues/150

It seems like at some point I already applied that patch and it didn't work, but I left the line in my init script. I've removed it, and now power mode starts without problem.

**Comment by lexcast** [comment]
it toggled twice on start up

**Comment by Heshan5** [comment]
I don't have this one config.cson
