### ISSUE TITLE
Highest Score

### ISSUE THREAD

**Issue by Markao17** [JoelBesada/activate-power-mode#215]
Hey,
First of all great package! Thank you for that..

I was working today and just crossed my mind "what was my highest combo score today"? Tried to search for it and didn't find anything. So i would like to suggest adding that to the package, something that shows my highest score (of any time or for session, not sure) as i think would be a lot fun, and add some competition kinda thing on some teams. 

Cheers, Great work.

**Comment by lexcast** [comment]
#221 is merged
