### ISSUE TITLE
Installing "activate-power-mode@0.3.2" failed

### ISSUE THREAD

**Issue by sangshuduo** [JoelBesada/activate-power-mode#22]
events.js:72
          throw er; // Unhandled  'error' event

Error: ENOENT, open '/Users/sangshuduo/.atom/packages/activate-power-mode/.npmignore'

---------------
ATOM 1.2.4

**Comment by lexcast** [comment]
Closing issues on old versions of this package.

Open again if the problem persists with the latest release.
