### ISSUE TITLE
Combo Max Reset

### ISSUE THREAD

**Issue by alexwasik** [JoelBesada/activate-power-mode#229]
## Issue
Cannot reset Combo Max

**Comment by jeffswt** [comment]
That's a big problem...

**Comment by ruifarfetch** [comment]
just click on cmd + alt + i (mac) and go to application->localstorage->find the entry of the max score and delete it. Basically this is a webview. What this command does is "inspect element" like in Chrome.

**Comment by salvacarrion** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/6052046/23438006/728da89c-fe10-11e6-88af-3aec6396c46a.png)

**Comment by lexcast** [comment]
fixed on #253
