### ISSUE TITLE
ERR. install error

### ISSUE THREAD

**Issue by Terry93** [JoelBesada/activate-power-mode#23]
it says that I got ERR when installing it using the atom package management tools.Here is the INFO:

gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | darwin | x64
gyp http GET https://atom.io/download/atom-shell/v0.34.0/node-v0.34.0.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at errnoException (net.js:905:11)
gyp ERR! stack     at TCP.onread (net.js:559:19)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.34.0" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/Terry_Yang/.atom
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok

**Comment by RangerMauve** [comment]
Seems you had an issue connecting to the internet, probably not an issue with the package itself, tbh

**Comment by Terry93** [comment]
@RangerMauve OK,maybe I should switch to another network

**Comment by Terry93** [comment]
Hey guys, I am now switching to another network, but it didn't work. what should I do? Thank you so much!

**Comment by Terry93** [comment]
seems I need to install nodejs? is that true?

**Comment by RangerMauve** [comment]
Are you still getting the same error? Might be a firewall or something like that blocking access to NPM. What command are you running to install the plugin?

**Comment by Terry93** [comment]
I solve my problem now! thank you so mu @RangerMauve it could happen as what you said
