### ISSUE TITLE
Can not change the toggle keymap

### ISSUE THREAD

**Issue by mengzyou** [JoelBesada/activate-power-mode#232]
As title, I set the below in *~/.atom/keymap.cson* :  

```
'atom-workspace':
  'ctrl-alt-a': 'activate-power-mode:toggle'
```

But still 'ctrl-alt-o' is active. 

Atom version: 1.11.2  
Activate-Power-Mode version: 1.1.0

**Comment by lexcast** [comment]
I think you can disable the package keybindings on the package settings.

**Comment by mengzyou** [comment]
@lexcast   
Yes, thank you! Disable the package keybindings, 'ctrl-alt-o' is not active, but my settings 'ctrl-alt-a' is still not working.  

![screenshot_20161108_142824](https://cloud.githubusercontent.com/assets/360603/20089139/d25fb520-a5bf-11e6-88e9-074915e83b6e.png)

**Comment by mengzyou** [comment]
@lexcast   

Sorry, my mistake, because the 'Ctrl-Alt-a' was used by KWin global keymap.  
Close this issue.  

Thanks a lot.
