### ISSUE TITLE
Deprecated selector in `activate-power-mode/styles/activate-power-mode.less`

### ISSUE THREAD

**Issue by idike** [JoelBesada/activate-power-mode#234]
In `activate-power-mode/styles/activate-power-mode.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .power-mode-canvas,
.power-mode-canvas` => `atom-text-editor.editor .power-mode-canvas,
.power-mode-canvas`

* `atom-text-editor::shadow .streak-container,
.streak-container` => `atom-text-editor.editor .streak-container,
.streak-container`

* `atom-text-editor::shadow .streak-container .title,
.streak-container .title` => `atom-text-editor.editor .streak-container .syntax--title,
.streak-container .title`

* `atom-text-editor::shadow .streak-container .max,
.streak-container .max` => `atom-text-editor.editor .streak-container .syntax--max,
.streak-container .max`

* `atom-text-editor::shadow .streak-container .bar,
.streak-container .bar` => `atom-text-editor.editor .streak-container .syntax--bar,
.streak-container .bar`

* `atom-text-editor::shadow .streak-container .counter,
.streak-container .counter` => `atom-text-editor.editor .streak-container .syntax--counter,
.streak-container .counter`

* `atom-text-editor::shadow .streak-container .counter.bump,
.streak-container .counter.bump` => `atom-text-editor.editor .streak-container .syntax--counter.syntax--bump,
.streak-container .counter.bump`

* `atom-text-editor::shadow .streak-container .exclamations,
.streak-container .exclamations` => `atom-text-editor.editor .streak-container .exclamations,
.streak-container .exclamations`

* `atom-text-editor::shadow .streak-container .exclamations .exclamation,
.streak-container .exclamations .exclamation` => `atom-text-editor.editor .streak-container .exclamations .syntax--exclamation,
.streak-container .exclamations .exclamation`

* `atom-text-editor::shadow .streak-container.reached .title,
.streak-container.reached .title` => `atom-text-editor.editor .streak-container.reached .syntax--title,
.streak-container.reached .title`

* `atom-text-editor::shadow .streak-container.reached .counter,
.streak-container.reached .counter,
atom-text-editor::shadow .streak-container.reached .exclamations,
.streak-container.reached .exclamations,
atom-text-editor::shadow .streak-container.reached .max,
.streak-container.reached .max` => `atom-text-editor.editor .streak-container.reached .syntax--counter,
.streak-container.reached .counter,
atom-text-editor.editor .streak-container.reached .exclamations,
.streak-container.reached .exclamations,
atom-text-editor.editor .streak-container.reached .syntax--max,
.streak-container.reached .max`

* `atom-text-editor::shadow .streak-container.reached .bar,
.streak-container.reached .bar` => `atom-text-editor.editor .streak-container.reached .syntax--bar,
.streak-container.reached .bar`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by nic611** [comment]
@idike I got the same problem with you.

**Comment by lexcast** [comment]
this will be fixed soon
