### ISSUE TITLE
Particles not showing after update to new Combo Mode Version

### ISSUE THREAD

**Issue by SirLemuel** [JoelBesada/activate-power-mode#240]
I recently updated the package to the new combo mode version 1.1.0 and although I see combo mode and the numbers increasing animation, the particles no longer appear. I checked the setting and the option is checked. I reinstalled and restarted my Mac and the issue persists.

**Comment by lexcast** [comment]
You need to reach 50 (default) in the combo mode to activate the other effects.
You can disable combo mode or set a lower activation threshold.

**Comment by SirLemuel** [comment]
Ah I see, this should be emboldened in the README.

**Comment by SirLemuel** [comment]
Thanks though, I should have caught that!

**Comment by lexcast** [comment]
Yes, indeed, I will update the readme to make it more clear.
