### ISSUE TITLE
Combo Breaker? Update broke the package.

### ISSUE THREAD

**Issue by Nanapus** [JoelBesada/activate-power-mode#244]
Hey, I had your package on Atom for a while now, but have not updated it for a long time. I just now updated the package for the new "Combo" feature (as well as sounds, and all the other new features), but now the screen shaking and particles don't seem to be working anymore (I do love the "Combo feature" though). Is this a local issue just for me or is this a bug in the package?

EDIT 1: Just to note, I run on Windows 10, and have tried all of the classic IT guy solutions to the issue.

**Comment by lexcast** [comment]
You need to reach 50 (default) in the combo mode to activate the other effects.
You can disable combo mode or set a lower activation threshold.

**Comment by Nanapus** [comment]
Okay, thanks!
