### ISSUE TITLE
Doesn't always load completely

### ISSUE THREAD

**Issue by apersonnamedmike** [JoelBesada/activate-power-mode#250]
I get the combo every time, but it doesn't show particles until I disable and re-enable it.

Running on Windows 10, with atom 1.13.0

**Comment by devnido** [comment]
i have same problem with win 10 and atom 1.13.0. activate-power-mode only show combo number, but never show particles.

**Comment by lexcast** [comment]
You need to reach 50 (default) in the combo mode to activate the other effects.
You can disable combo mode or set a lower activation threshold.

**Comment by apersonnamedmike** [comment]
Ohhhh..... Thanks. I thought I'd seen all the settings. Sorry.
