### ISSUE TITLE
Screen Shake Out of Control

### ISSUE THREAD

**Issue by Shivang-Bhandari** [JoelBesada/activate-power-mode#251]
Hi ,
The screenshake due to the package has suddenly got out of control and somehow now after the trigger of active power mode the screen starts scrolling on it's own and I have to scroll down to check where am i doing my code.

**Comment by Shivang-Bhandari** [comment]
@JoelBesada Facing this issue only with .md files

**Comment by lexcast** [comment]
It is still happening? I can not reproduce

**Comment by Shivang-Bhandari** [comment]
@lexcast only happening for .md files on my end

**Comment by Shivang-Bhandari** [comment]
i played around with some of the package settings, however i removed the package and reinstalled it and now it seems to do fine

**Comment by lexcast** [comment]
Great. Thank you
