### ISSUE TITLE
Why use @throttledPlayAudio instead of @playAudio.play().

### ISSUE THREAD

**Issue by Jerajo** [JoelBesada/activate-power-mode#256]
Label:question
Hello, inside power-editor.coffee, there are some functions that are called by @throttled

I'm wondering what is the reason for use @throttledPlayAudio() instead of @playAudio.play() directly.
It do the same and quicker.

`if @getConfig "playAudio.enabled"`
      `#@throttledPlayAudio()`
      `@playAudio.play()`

Also I tried to create my own function using the @throttled call method but I got a error 
"Uncaught TypeError: this.getConfig is not a function" I recive that error because I didn't include the
function: `getConfig: (config) ->` inside my file.
which return: `atom.config.get "activate-power-mode.#{config}"`

if some one can explain me the functionality of @throttled call methord, I will thank you.
Thanks for the help.

**Comment by lexcast** [comment]
This is the documentation for that function https://lodash.com/docs/4.17.4#throttle
Basically is used to avoid calling a function too many times, for performance reasons in the case of the screen shake. 
If you need to use @ (this) inside a throttled function you need to bind it: .bind(this)

**Comment by Jerajo** [comment]
Thanks @lexcast
