### ISSUE TITLE
Play Background Music and Exclamation Audio.

### ISSUE THREAD

**Issue by Jerajo** [JoelBesada/activate-power-mode#257]
### Hello Guys. <h3> 

**I made two functions `play-backgrund-audio` and `play-exclamation-audio`.**

1. `play-backgrund-audio`: This function play background music while leftTimeout > 0. and

2. `play-exclamation-audio`: This funtion play Eclamation sound each time apear an exclamation or if leftTimeout == 0.

The onlly thing is that those functions need to be executed when `leftTimeout > 0 or leftTimeout == 0`. I tried to implement those functions inside of `power-editor.coffee`  but there didn't work. Because I can't pass by reference the variable from `@comboMode` In the only place I got it to work was inside of `combo-mode.coffee`. 

I thing could be more practical if the timeout script is implemented outside of  `combo-mode.coffee`, because future funtions could need the leftTimeout value.

Also I would like to know if there is a way to get it work with out needing to copy all the timeout script inside of each function who need it, or if there is a way to implement the function directly in `power-editor.coffee`. 

@JoelBesada @lexcast @nathanchapman could you tell me what do you think bout those functions.

Here are the functions if you want to check it.
[play-baackground-audio.txt](https://github.com/JoelBesada/activate-power-mode/files/835502/play-baackground-audio.txt)
[play-exclamation-audio.txt](https://github.com/JoelBesada/activate-power-mode/files/835503/play-exclamation-audio.txt)

if you what to test the functions [here](https://github.com/Jerajo/activate-power-mode) is my commit.

**Comment by Jerajo** [comment]
Here is the `confing-scema` i use for the new function.
[config-schema.txt](https://github.com/JoelBesada/activate-power-mode/files/835735/config-schema.txt)

I would like to commit my changes, but first I want to know what do you think bout this feature.

**Comment by Jerajo** [comment]
I have already realized that `combo-mode.coffee` use `lodash.debounce` to implement the time of function execution. and the leftTimeout variable is only used for draw the bar. :sweat_smile:

I think, I can do the same with `play-background-music.coffee` and `play-exclamation-audio.coffee`
I will use `lodash.debounce` to indicate when the audio will be played and stopped.

**Comment by lexcast** [comment]
Hi @Jerajo 
Sounds like a great addition for the combo mode. I'm working in a service api to handle combo events maybe it can use that. Something like `combo.onChangeStreak(callback)`

**Comment by Jerajo** [comment]
I have the additions almost ready. I just need to implement some performance updates. 
I realized, the editor became too slow, when I left a key press for 10 or more seconds.

So that I try to detect wend I left a key pressed with this code.

```
onChange: (e) ->
    pos = @editor.getCursorBufferPosition()
    row = pos.row
    col = pos.column
    currentKey = @editor.getTextInBufferRange([
       [row,col-1],
       [row,col]
    ])
    if @previousKey is currentKey
      return null
    else
      #code here...
```

I not sure, is it will be better, if is implemented were the function `@editorChangeSubscription ` if declare or inside of `onChange: (e) ->`.

**Comment by lexcast** [comment]
Take a look on the #264, it provides some events on the combo.
