### ISSUE TITLE
Flickering on fullscreen

### ISSUE THREAD

**Issue by AaronBurmeister** [JoelBesada/activate-power-mode#274]
Atom is flickering when using atom in fullscreen mode with activate-power-mode enabled.
I am using Linux Mint 18.1.

**Comment by lexcast** [comment]
Hi @AaronBurmeister 
Can you share a recording? I can't reproduce on Ubuntu 17.04.

**Comment by AaronBurmeister** [comment]
Hello @lexcast.
Thank you for your fast response.

I am sorry but I was not able to find a working screen recorder yet.
This is why I had to record my screen with a phone: https://www.dropbox.com/s/r1eqah68cia8z1j/Video%2031.05.17%2C%2023%2000%2035.mov?dl=0

Please focus on the tree view and the minimap.

**Comment by lexcast** [comment]
this happens only with this package enabled?

**Comment by AaronBurmeister** [comment]
Yes, and only when the combo timeout indicator (below the currend combo) is visible

**Comment by lexcast** [comment]
That's weird. I've confirmed the issue only with the minimap when the screen shakes.
Try disabling the screen shake in the package's settings to see if is that the problem.

**Comment by AaronBurmeister** [comment]
I disabled first screen shake and then particle effects but both didn't fix it.
It get's only fixed when disabling combo mode.

**Comment by AaronBurmeister** [comment]
I am closing this issue now as this doesn't seem to be related to activate-power-mode in particular but more to Linux Mint or electron and there doesn't seem to be other users affected.
