### ISSUE TITLE
Api functions in file based user flows

### ISSUE THREAD

**Issue by triforce930** [JoelBesada/activate-power-mode#283]
Wanted to show "Auto-Complete!!" exclamation whenever the text is replaced with something longer + give some bonus combo levels for it. But couldn't find a way to show exclamations on combo counter. Is there a way to do it from the User File flow?

**Comment by lexcast** [comment]
Hi @triforce930 
The custom exclamation would be great to add in the modifier option for the combo. https://github.com/JoelBesada/activate-power-mode/wiki/Flow#modifier-data I was thinking in that originally but I guess I forgot it.

Not sure about the combo levels as it relays on a setting to know when to reach a level, but I'm open to ideas.

**Comment by triforce930** [comment]
I meant, increasing the combo counter by some amount, when I said bonus combo levels.

So if you ever decide to program the custom exclamation modifier, can you also add a color option for it?

Many thanks for the answer :+1:

**Comment by lexcast** [comment]
Hi @triforce930 sorry for the delay.
I've added an exclamation modifier. For the color option you can use 'exclamation_type' to add a class to the exclamation. Using this class you can set colors, font size or font family with css.
