### ISSUE TITLE
add customizable combo limit

### ISSUE THREAD

**Issue by djh1997** [JoelBesada/activate-power-mode#289]
would like to be able to have the effects limit with combo customizable

**Comment by Jerajo** [comment]
what do you mean by effects limit? max particle count?
could you add more details to your question?

**Comment by djh1997** [comment]
an adjustable character count between first press and the effects showing.
so that you can adjust the characters before the combo effects (shake ,particles,sounds) start happening

**Comment by Jerajo** [comment]
I think I understand what you want. You are talking about the `onInput event`.

> [Wiki > Plugins > Plugin object.](https://github.com/JoelBesada/activate-power-mode/wiki/Plugins)

There is where you can do something during streak count.

```javascript
// When the user writes something. You get the cursor, 
// the screen position of the input, an input object 
// and data processed by the flow.
onInput(cursor, screenPosition, input, data) {}
```

> @djh1997 
    _"an adjustable character count between first press and the effects showing
    so that you can adjust the characters before the combo effects (shake ,particles,sounds) start happening"_

@lexcast is fixing the error that has the `onInput event` to let you do something before the combo reach the `activation threshold`. Just wait until the next release.

**Comment by lexcast** [comment]
I think @djh1997 is just asking for the `Activation threshold` setting, the rendering of this setting was fixed recently.
@djh1997 by default this setting is set with a minimum of 20.

**Comment by djh1997** [comment]
That's what I ment that everyone
