### ISSUE TITLE
New ideas for activate-power-mode.

### ISSUE THREAD

**Issue by Jerajo** [JoelBesada/activate-power-mode#299]
On the context menu only appear the toggle command, will be great if also appear the commands, Reset Max Combo and Select Effects.

![image](https://user-images.githubusercontent.com/26252994/29191225-005535f0-7deb-11e7-9099-9cc44cae3510.png).

I also noticed that the commands aren't in the [README.md](https://github.com/JoelBesada/activate-power-mode/blob/master/README.md) file. Neither the news settings. 

This may cause confusion to the new users of the package.

**Comment by Jerajo** [comment]
Also think the [README.md](https://github.com/JoelBesada/activate-power-mode/blob/master/README.md) file should have an section for plugins.

**something like**.

<h1>Plugins</h1>

* [Activate-Background-Music](https://github.com/Jerajo/activate-background-music)
* [Activate-killer-Instinct-Exclamations](https://github.com/Jerajo/activate-killer-instinct-mode)

**Comment by Jerajo** [comment]
@lexcast what do you think about insert a **Youtube** video on the [README.md](https://github.com/JoelBesada/activate-power-mode/blob/master/README.md) file?

A video showing all the package features, something like this.

![image](https://user-images.githubusercontent.com/26252994/29229619-5e963214-7ead-11e7-8356-5624c4a753e9.png)

and I can make the video.

**Comment by lexcast** [comment]
Hi @Jerajo 
The context menu sounds fine to me.
About the README I would like to improved a bit or at least update it with the new settings as you said. Maybe move some sections to a wiki page.
About the youtube video I'm not sure.
Btw in the readme of https://github.com/Jerajo/activate-background-music it is not displayed, I see `<iframe` as text.

**Comment by lexcast** [comment]
I really like the plugins section. Just not sure if it should be in the README or the wiki (maybe in both).

**Comment by Jerajo** [comment]
> @lexcast 
    _About the youtube video I'm not sure.
    Btw in the readme of https://github.com/Jerajo/activate-background-music it is not displayed, I see 
    <iframe as text._

Yes is true I doesn't know why on **github** page the `<iframe>` appear as text. But **ATOM** recognises it.

![image](https://user-images.githubusercontent.com/26252994/29237105-1d746868-7ee5-11e7-8fcc-51c5be4eb631.png)
