### ISSUE TITLE
jjjUncaught ReferenceError: ResizeObserver is not defined

### ISSUE THREAD

**Issue by sam-hansen** [JoelBesada/activate-power-mode#313]
[Before submitting, please enter steps to reproduce:]

1. ...
2. ...

**Learn IDE Package**: 3.0.0
**Learn IDE Core**: 3.0.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home Insider Preview
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package 2.5.0

### Stack Trace

Uncaught ReferenceError: ResizeObserver is not defined

```
At C:\Users\samue\.atom\packages\activate-power-mode\lib\canvas-renderer.coffee:54

ReferenceError: ResizeObserver is not defined
    at Object.initResizeObserver (/packages/activate-power-mode/lib/canvas-renderer.coffee:54:27)
    at Object.enable (/packages/activate-power-mode/lib/canvas-renderer.coffee:19:6)
    at Object.enable (/packages/activate-power-mode/lib/plugin/power-canvas.coffee:11:13)
    at /packages/activate-power-mode/lib/plugin-registry.coffee:79:18
    at Config.module.exports.Config.observeKeyPath (/app.asar/src/config.js:616:7)
    at Config.module.exports.Config.observe (/app.asar/src/config.js:141:21)
    at Object.observePlugin (/packages/activate-power-mode/lib/plugin-registry.coffee:76:46)
    at Object.enable (/packages/activate-power-mode/lib/plugin-registry.coffee:21:8)
    at Object.enable (/packages/activate-power-mode/lib/plugin-manager.coffee:68:21)
    at Object.enable (/packages/activate-power-mode/lib/power-editor.coffee:7:20)
    at Object.enable (/packages/activate-power-mode/lib/activate-power-mode.coffee:43:18)
    at Object.toggle (/packages/activate-power-mode/lib/activate-power-mode.coffee:39:38)
    at /packages/activate-power-mode/lib/activate-power-mode.coffee:28:10
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.5.0 
ada-wave-syntax 0.2.0 
apco-black-ui 1.1.0 
astronomical-ui 0.22.5 
atom-clock 0.1.15 
atom-gooey-syntax 1.0.0 
atom-material-ui 2.0.4 
atom-panda-syntax 0.18.0 
atom-surfs-up-ui 0.1.0 
atomic-design-ui 1.1.2 
atomic-monokai-syntax 1.2.1 
base16-syntax 1.8.1 
black-pearl-i-i 0.5.0 
blossom-syntax 0.5.0 
blossom-ui 0.3.0 
bright-dark-syntax 0.4.1 
bright-dark-ui 0.5.1 
chestnut-light-atom-syntax 0.2.1 
contrast-ui 0.53.0 
dash-syntax 0.3.0 
dash-ui 0.4.2 
evangelism-syntax 0.13.0 
file-icons 2.1.11 
gl-light-syntax 3.0.0 
glacier-dark-ui 0.5.0 
gzl-ui 1.0.0 
hacker-dream-syntax 1.4.8 
hacker-dream-ui 1.1.0 
improved-dusk-syntax 2.1.0 
keyboard-scroll 0.7.0 
Lucario 2.2.0 
markdown-writer 2.7.2 
matte-black-ui 0.2.0 
moonbeam-syntax 0.8.1 
ninja-ui-syntax 0.1.4 
ninja-ui-vibrant-syntax 3.1.0 
now-syntax 0.2.4 
platformio-ide-terminal 2.6.0 
pristine-ui 1.1.10 
proton-light 0.2.0 
pure-syntax 0.3.0 
seti-syntax 1.1.3 
seti-ui 1.9.0 
seti-ui-beta 0.1.1 
tool-bar-markdown-writer 0.3.0 
```

**Comment by lexcast** [comment]
Hi @sammihansen 
What is Learn IDE Package/Core? it is a "special" atom?

**Comment by sammihansen** [comment]
Hi @lexcast 
I’m so sorry! I was using the “learn ide” from [Lambda School](https://lambdaschool.com) when this occurred. I wasn’t aware the issue had been submitted to you.  I will go ahead and close it.

**Comment by lexcast** [comment]
Don't worry @sammihansen 
Even if it is a "special" atom version if it is really a bug, this issue should be reopen.

**Comment by sammihansen** [comment]
OK. I have re-opened the issue.  Come to think of it that would be fun to be able to use power-mode in the learn-ide. :smile:

**Comment by lexcast** [comment]
This is failing because `ResizeObserver` does not exist yet in the electron version that learn IDE is using (v1.3) it needs at least electron v1.6. 
Not sure which version of atom is learn ide using, but the fix here is to use an old version of this package before using the `ResizeObserver` api. Probably [v2.3.0](https://github.com/JoelBesada/activate-power-mode/releases/tag/v2.3.0).

**Comment by Riroaki** [comment]
@lexcast I fail to use the mode too......TAT and for the same reason "ResizeObserver is not defined"
but I don't know what happened......I've just downloaded atom today

**Comment by guojindai** [comment]
update Atom to 1.23.3, this error is gone
