### ISSUE TITLE
very much hope to support vscode

### ISSUE THREAD

**Issue by hubluesky** [JoelBesada/activate-power-mode#314]
Now vscode has a similar, [https://github.com/hoovercj/vscode-power-mode](url)
but too ugly, really hope to support vscode, [https://code.visualstudio.com/](url)
thank you.(google translate)
现在vscode有一个类似的，但是太丑了，真心希望能支持vscode，谢谢。

**Comment by lexcast** [comment]
Hi @hubluesky 
For other editors implementations see https://github.com/codeinthedark/awesome-power-mode.
The package you mention are making good efforts improving the look and feel of the particles animation hoovercj/vscode-power-mode#10.

**Comment by hoovercj** [comment]
@hubluesky I hope you'll look at the improvements I made in v2 of vscode power mode. If you have suggestions you can open an issue at https://github.com/hoovercj/vscode-power-mode/issues/new

![demo](https://github.com/hoovercj/vscode-power-mode/blob/master/images/demo-presets-particles.gif)

**Comment by hubluesky** [comment]
@hoovercj OK, I'll try it. Thanks.
