### ISSUE TITLE
Packages that depend on modules that contain C/C++ code will fail to install

### ISSUE THREAD

**Issue by Simon-wu** [JoelBesada/activate-power-mode#319]
win 10 
atom 1.20.1
Installing “activate-power-mode@2.5.0” failed.Show output…
Compiler tools not found
Packages that depend on modules that contain C/C++ code will fail to install.
Read here for instructions on installing Python and Visual Studio.
Run apm install --check after installing to test compiling a native module.

**Comment by Gobayli** [comment]
Echo this

**Comment by lexcast** [comment]
Hi @Simon-wu 
Can you install another package? 
or this just happens when trying to install activate power mode package?

**Comment by Simon-wu** [comment]
I can install another package.
I used atom 1.20.1

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lexcast** [comment]
@Simon-wu can you paste the output of:
```
apm -v
```
and
```
apm install --check
```
also on atom's forum there are already some hints about this problem:
https://discuss.atom.io/t/installing-packages-fails-every-time-windows-8-1-atom-1-0/17990
https://discuss.atom.io/t/cannot-install-packages-with-1-0-3/19395/30

**Comment by Gobayli** [comment]
@Simon-wu it works for me now. What I did was:
1. Updated my atom to 1.20.1 the latest one (I used to use 1.18) 
2. Uninstalled this package and restart atom
3. Installed this package

**Comment by Simon-wu** [comment]
may be network problem

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by maqingbo** [comment]
如使用了代理，可以参考：https://segmentfault.com/a/1190000008378368

**Comment by Ali332** [comment]
C:\Users\Ali\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:144
        throw er
        ^

Error: EPERM: operation not permitted, read
    at Object.fs.readSync (fs.js:675:18)
    at Object.readSync (C:\Users\Ali\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:138:28)
    at tryReadSync (fs.js:540:20)
    at Object.fs.readFileSync (fs.js:575:19)
    at Object.Module._extensions..js (module.js:645:20)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)

**Comment by Ali332** [comment]
this happens while installing a package someone help
