### ISSUE TITLE
I need your help please

### ISSUE THREAD

**Issue by astrolemonade** [JoelBesada/activate-power-mode#336]
I recently saw this package and I want to install it.
What is the font and the color scheme from the description of this package? The ones from this:
![10f16456-9c65-11e5-8af4-265f01fc83a0](https://user-images.githubusercontent.com/35623921/43365676-f41afa72-9338-11e8-9cf2-067825713933.gif)

I really hope someone will answer to me

**Comment by nathanchapman** [comment]
@cata0309 I'm not 100% on this, but it looks to be [Hack](https://sourcefoundry.org/hack/) with the  [One Dark Pro theme](https://atom.io/themes/one-dark-syntax). Hope this helps.
