### ISSUE TITLE
cannot edit more than one file

### ISSUE THREAD

**Issue by SpaceDouble7** [JoelBesada/activate-power-mode#36]
if I open one more file, the active-power-mode cannot work in the second file, and meanwhile the first file will just shake without light.

**Comment by wanglerwong** [comment]
I met the same issue!

**Comment by cxwithyxy** [comment]
the same issue too !

**Comment by huytd** [comment]
Same issue too, #42 is possible dupplicated with this issue

**Comment by yongzhidai** [comment]
same issue too

**Comment by JoelBesada** [comment]
Fixed in 0.4.0.
