### ISSUE TITLE
Particle effects constantly above the cursor

### ISSUE THREAD

**Issue by c19** [JoelBesada/activate-power-mode#39]
at the very beginning of a file. it's right at the cursor.
and the particles appears above the cursor farther when the cursor is at lower place of a file.
at 550 line it's about 5 lines above.
and it's constantly at the beginning of a line. no matter where the cursor is in a line.

**Comment by c19** [comment]
tried, restart and togglings. now particle effects moves horizontally with the cursor. but still above it.
and the color is the color where particle effects at. guess it somehow mistakenly think the cursor is above where cursor actually is.

**Comment by c19** [comment]
atom 1.2.4 and active-power-mode 0.3.2
on a js file. it's abnormal. on a newly create blank file. it's good.

**Comment by c19** [comment]
seems under some circumstances, @editor.getScrollTop() would drift towards up.

**Comment by lexcast** [comment]
are you using soft wrap?

**Comment by lexcast** [comment]
already fixed, use the latest version
