### ISSUE TITLE
Particle offset seems to be off in 0.3.2

### ISSUE THREAD

**Issue by karai17** [JoelBesada/activate-power-mode#4]
Particles seem to be exploding behind the typed letter, not on top of it.

**Comment by raulsntos** [comment]
It seems to have something to do with scrolling, when I'm at the top of the document everything seems fine but when I scroll down the particle effect appears a few lines above where I'm typing.

**Comment by tzm41** [comment]
+1. At the top of the document they are fine, but as I scroll down, they are getting more and more above the cursor, and finally disappears off the top edge of the window.

**Comment by Vtec234** [comment]
+1. For me the top-offset works fine, but particles appear behind (to the left from) the cursor when using hard tabs. When writing on a non-indented line or using soft tabs particles appear in the correct place.

**Comment by lexcast** [comment]
already fixed, use the latest version
