### ISSUE TITLE
no Particles while vim-mode enabled

### ISSUE THREAD

**Issue by thinkinnight** [JoelBesada/activate-power-mode#41]
Very impressive! Greate job! I love this plugin.
And while I am using this plugin, I found when vim-mode is enabled, while typing, only shake but no paticles shown.
I wonder if this is a problem and if I can use both vim-mode and activate-power-mode, it would be greate.
Thanks again for your good job!

**Comment by jmexe** [comment]
Same here

**Comment by lexcast** [comment]
this is issue is still happening with the latest version?

**Comment by lexcast** [comment]
Closing issues on old versions of this package.

Open again if the problem persists with the latest release.
