### ISSUE TITLE
no sparkling/Particle effect 

### ISSUE THREAD

**Issue by anthvo** [JoelBesada/activate-power-mode#48]
no Particle effect 
OS X 10.10.5

**Comment by pizilovebaby** [comment]
@anthvo If no activate?  My Mac can

**Comment by anthvo** [comment]
@pizilovebab  activated. only the shaking...

**Comment by thinkinnight** [comment]
@anthvo Do you have any other plugin activated? I have vim-mode activated, then it only have shaking. And after disabled vim-mode, it can work. I also raised an issue.

**Comment by trickysky** [comment]
the same problem on my mac

**Comment by pizilovebaby** [comment]
So do I. It is perfect when I edit the first text. However,when the other text is opened and then switch back to the first one,it's just shaking no sparkling....buggy

**Comment by jianbingfang** [comment]
same problem on Win10. : (

**Comment by anthvo** [comment]
@thinkinnight the problem exists whether i turned vim-mode on or not

**Comment by lexcast** [comment]
the issue here is when working with vim-mode on?

**Comment by lexcast** [comment]
Closing issues on old versions of this package.

Open again if the problem persists with the latest release.
