### ISSUE TITLE
有时会不起作用

### ISSUE THREAD

**Issue by yongzhidai** [JoelBesada/activate-power-mode#49]
有时会不起作用

**Comment by dmPty** [comment]
#6 去看下这个
readme已经说了现在bug很多，自己折腾或者等主仓库更新吧

**Comment by jason19659** [comment]
按ctrl+alt+r后再按ctrl+alt+o 激活

**Comment by leguang** [comment]
为什么我的按ctrl+alt+r是保存
ctrl+alt+o是弹出选择文件框
我无语了

**Comment by MwumLi** [comment]
重启一下就好了。bug有点多

**Comment by Shyam-Chen** [comment]
Ctrl + Alt + R 後再 Ctrl + Alt + O，我有成功

**Comment by lexcast** [comment]
is this issue fixed?

**Comment by Shyam-Chen** [comment]
@lexcast 
it can be closed

**Comment by lexcast** [comment]
thanks @Shyam-Chen
