### ISSUE TITLE
Seems Can not cooperate with vim-mode

### ISSUE THREAD

**Issue by IdiosyncraticDragon** [JoelBesada/activate-power-mode#60]
I have only two plugins:  activate-power-mode, and vim-mode.
But active-power-mode has 1 deprecation:
This method is deprecated on the model layer. Use TextEditorElement::pixelPositionForScreenPosition instead.

This situation is if I disable vim-mode, and enable activate-power-mode, it works, just the animation is not so fluency, but if I open the two plugins together, the activate-power-mode just doesn't work.

Does anyone the same problem?

**Comment by lsqshr** [comment]
@IdiosyncraticDragon Vim-Mode support + 1

**Comment by lsqshr** [comment]
@IdiosyncraticDragon I just tried it again. Seems like the problem goes away if you call Window:Reload 
Stated here: https://atom.io/packages/activate-power-mode

**Comment by IdiosyncraticDragon** [comment]
Thank you! I just tried Window:Reload,  it is ok for the first tag after Window:Reload, but if I create a new tag and try to tiger active-power-mode by ctrl+alt+o, it does not work. It seems nature because the author in early version,  it only affect current tab, if we want try a new tab, we need Window:Reload again....
