### ISSUE TITLE
Positioning issue when use tab instead of space

### ISSUE THREAD

**Issue by Ariex** [JoelBesada/activate-power-mode#66]
when code is indent with tab, seems the animation position is not correct; and when change tabs to space this issue disappears

**Comment by EarMaster** [comment]
I can confirm this. The location is shifted to the left, when using tabs for indentation.

**Comment by marcoms** [comment]
Me too... Seems like tabs are being interpreted as having the width of a single character

**Comment by lexcast** [comment]
already fixed, use the latest version
