### ISSUE TITLE
Add turn off vibration option

### ISSUE THREAD

**Issue by hfz1991** [JoelBesada/activate-power-mode#68]
Thanks for this great plugin. I have been using this plugin for the whole afternoon. 
I found that eyes will be easy to get tired because of vibration.
Can you add a option to remove vibration?
Thanks a lot! I will continue to support.

**Comment by geocine** [comment]
https://github.com/JoelBesada/activate-power-mode/issues/63

**Comment by JoelBesada** [comment]
Fixed in 0.4.0.
