### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clearRect' of undefined

### ISSUE THREAD

**Issue by wziyanqq** [JoelBesada/activate-power-mode#7]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.3.2

### Stack Trace

Uncaught TypeError: Cannot read property 'clearRect' of undefined

```
At /Users/longinus/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:101

TypeError: Cannot read property 'clearRect' of undefined
    at Object.module.exports.ActivatePowerMode.drawParticles (/Users/longinus/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:101:13)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "about"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.3.2

# Dev
No dev packages
```

**Comment by zqcloveping** [comment]
I also have this problem. You have to intsall atom-material-ui theme to solution the problem.
中文:我也遇到了这个问题。你应该安装atom-material-ui这个主题来解决上面的问题

**Comment by lexcast** [comment]
is this still happening with the latest version?

**Comment by lexcast** [comment]
Closing issues on old versions of this package.

Open again if the problem persists with the latest release.
