### ISSUE TITLE
I like it,but

### ISSUE THREAD

**Issue by Javacym** [JoelBesada/activate-power-mode#74]
I like this,it's cool,but i do not like  screen shake ,can i setting ?? and will add a cool sound or music like 
Chopin,Mozart..it will fucking cool ^_^

**Comment by fanbinjim** [comment]
i couldn't agree more~~

**Comment by andytaiyi** [comment]
https://github.com/JoelBesada/activate-power-mode/issues/63

**Comment by andytaiyi** [comment]
find your answer at https://github.com/JoelBesada/activate-power-mode/issues/63

**Comment by lexcast** [comment]
fixed the shake option, and the sound is duplicated #21
