### ISSUE TITLE
Unable to install it using atom pakage management

### ISSUE THREAD

**Issue by ghostbody** [JoelBesada/activate-power-mode#75]
![image](https://cloud.githubusercontent.com/assets/8371330/11608831/b5a86dce-9b29-11e5-8081-0ffeb24e69aa.png)
The Error is above.

**Comment by lexcast** [comment]
are you behind a proxy? seem to be this issue atom/apm#322

**Comment by lexcast** [comment]
Closing issues on old versions of this package.

Open again if the problem persists with the latest release.
