### ISSUE TITLE
TextEditor.pixelPositionForScreenPosition is deprecated.

### ISSUE THREAD

**Issue by super-mario123** [JoelBesada/activate-power-mode#8]
This method is deprecated on the model layer. Use `TextEditorElement::pixelPositionForScreenPosition` instead
```
TextEditor.pixelPositionForScreenPosition (F:\download\atom-windows\Atom\resources\app.asar\src\text-editor.js:2714:9)
Object.spawnParticles (C:\Users\dings\.atom\packages\activate-power-mode\lib\activate-power-mode.coffee:67:26)
Object.throttledSpawnParticles (C:\Users\dings\.atom\packages\activate-power-mode\node_modules\lodash.throttle\node_modules\lodash.debounce\index.js:182:23)
Object.onChange (C:\Users\dings\.atom\packages\activate-power-mode\lib\activate-power-mode.coffee:48:5)
Emitter.emit (F:\download\atom-windows\Atom\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
TextBuffer.applyChange (F:\download\atom-windows\Atom\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:631:20)
```

**Comment by cheny95** [comment]
This method is deprecated on the model layer. Use TextEditorElement::pixelPositionForScreenPosition instead

TextEditor.pixelPositionForScreenPosition - /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2680:9
Object.spawnParticles - /Users/iMc/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:67:26
Object.throttledSpawnParticles - /Users/iMc/.atom/packages/activate-power-mode/node_modules/lodash.throttle/node_modules/lodash.debounce/index.js:182:23
Object.onChange - /Users/iMc/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:48:5
Emitter.emit - /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11
TextBuffer.applyChange - /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:626:20

**Comment by lexcast** [comment]
already fixed
