### ISSUE TITLE
Doesn't quite work with mardown

### ISSUE THREAD

**Issue by BenP51** [JoelBesada/activate-power-mode#80]
When writing markdown, it hits an bug if your writing is wrapped and you go past the length of the screen. In other words, when you have soft word wrapping on and write a line in an md file longer than the screens width, the power mode cursor will sometimes disappear and sometimes stop moving and stay on a previous line. The screen does continue to shake still though.

**Comment by xtutu** [comment]
I encountered a similar problem.
when I open markdown preview, the particles position is strange.

**Comment by lexcast** [comment]
already fixed, use the latest version
