### ISSUE TITLE
抖动范围和烟花效果两大bug

### ISSUE THREAD

**Issue by wuzhengqiang** [JoelBesada/activate-power-mode#82]
①请不要整个页面抖动好吗？很难受的呢。希望保留烟花去除整个页面抖动！
②切换到别的地方再回到软件，只有抖动效果，没有烟花效果啦！得重新启用才有。

**Comment by jason19659** [comment]
plz checkout the new version 0.41 and close by yourself

**Comment by lexcast** [comment]
this should be fixed already
