### ISSUE TITLE
Auto open on Atom starting!

### ISSUE THREAD

**Issue by itkang** [JoelBesada/activate-power-mode#87]
When Atom is starting,Need press control+alt+o to open, Many times forget it! If it can configuration on setting!

**Comment by opus1269** [comment]
:thumbsup:

**Comment by chl1996** [comment]
🆙

**Comment by raulsntos** [comment]
Maybe it would be nice if it remembered if it was activated when Atom was closed so that it remains activated after restarting Atom

**Comment by kuoruan** [comment]
Add a line to your init.cofee
```
atom.commands.dispatch(atom.views.getView(atom.workspace), 'activate-power-mode:toggle')
```

**Comment by itkang** [comment]
atom.commands.dispatch(atom.views.getView(atom.workspace), 'activate-power-mode:toggle')
It working.
