### ISSUE TITLE
Hope to have vs code version

### ISSUE THREAD

**Issue by ryj438591419** [JoelBesada/activate-power-mode#90]
Hope to have vs code version

**Comment by lexcast** [comment]
https://github.com/LiamMorrow/Visual-Studio-Power-Mode

**Comment by drew-isnotnull** [comment]
^ That's for Visual Studio, not VSCode

**Comment by malarinv** [comment]
apparently it [isn't implementable](https://github.com/Microsoft/vscode/wiki/Requested-Extensions) currently in vscode

**Comment by matheusalxds** [comment]
Rly, not working in vs code =/
