### ISSUE TITLE
Particles not following cursor in wrap mode

### ISSUE THREAD

**Issue by ardianta** [JoelBesada/activate-power-mode#91]
In soft wrap view, Particles not following cursor [https://youtu.be/pCZRB48yW0s](https://youtu.be/pCZRB48yW0s)

**Comment by blahlicus** [comment]
can confirm, the power mode particles' location is not accounted for when word wrap is enabled

**Comment by ynyyn** [comment]
Besides, the following lines after the soft wrap line will also have the problem

**Comment by lexcast** [comment]
already fixed, use the latest version
